# Generated by Django 6.0.1 on 2026-01-08 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200, validators=[django.core.validators.MaxLengthValidator(8)]),
        ),
    ]
